const en = {
  translation: {
    common: {
      welcome: "Welcome",
      submit: "Submit",
      cancel: "Cancel",
      yes: "Yes",
      no: "No",
      next: "Next",
      prev: "Previous",
    },
    referralStep: {
      step1: "Your Information",
      step2: "Referral Code",
      step3: "Verify Code",
      title: "Win a 2025 Nissan Versa!",
      proccesing: "Processing your registration...",
    },
    weeklyTv: {
      form: {
        title: "Weekly Smart TV Sweepstake",
        subtitle: 'Win a brand new 55" Smart TV - Enter now for your chance!',
        note: "All fields are required. US phone & ZIP code only.",
      },
    },
    winATv: {
      title: "Win a 55'' TV December 25",
      notConfigured: "This giveaway isn't configured yet. Please check back soon.",
    },
    login: {
      title: "Login with your phone",
      phoneLabel: "Phone number",
      sendOtp: "Send OTP",
      enterOtp: "Enter the OTP sent to",
      verifyOtp: "Verify OTP",
      changePhone: "Change number",
      errorInvalidPhone: "Phone number not registered",
      errorInvalidOtp: "Invalid OTP",
      loading: "Loading...",
    },
    home: {
      registerInStore: "Register in our store",
    },
    store: {
      openInMaps: "Open in Google Maps",
    },
    form: {
      firstName: "First Name",
      lastName: "Last Name",
      phone: "Phone",
      email: "Email",
      zip: "ZIP Code",
      referralCode: "Referral code",
      referralCodeNotice: "If not, you can click next step button.",
      supermarket: "Supermarket",
      selectSupermarket: "Enter supermarket name",
      referralInfoTitle: "Referral Information",
      referralInfoSubtitle: "Help us track your referral",
      referralCodePlaceholder: "HAVE A REFERRAL CODE? ADD IT HERE",
      errors: {
        firstName: {
          required: "First name is required",
          max: "First name must be less than 50 characters",
        },
        lastName: {
          required: "Last name is required",
          max: "Last name must be less than 50 characters",
        },
        phone: "Phone number must be in format (123) 456-7890",
        email: "Enter a valid email address",
        zip: "ZIP code must be 5 digits",
        otp: "OTP must be exactly 6 digits",
        supermarket: {
          required: "Please select a supermarket",
          missingSweepstake: "Missing sweepstake configuration",
        },
      },
    },
    profile: {
      title: "Your Profile",
      coupons: "Your Entries",
      referralLink: "Your Referral Link",
      referralCode: "Your Referral Code",
      copyLink: "Copy Link",
      copyCode: "Copy Code",
      registeredFriends: "Friends registered with your link",
      noReferrals:
        "You don't have any referrals yet. Share your link to get more chances!",
      selectStore: "Select store",
      shareWhatsapp: "Share on WhatsApp",
      shareFacebook: "Share on Facebook",
      share: "Share",
      mainReferralLink: "Referral Link",
      copySuccess: "Link copied!",
      codeCopySuccess: "Code copied to clipboard",
      inviteMore: "Keep sharing and good luck in the giveaway!",
    },
    referral: {
      shareTitle: "Invite, Share, and Win!",
      shareDescription: "Share your exclusive link and boost your chances.",
      copy: "Copy the link and send it via WhatsApp, Messenger, Facebook, SMS, or anywhere!",
      referralExtra:
        "Each friend who registers with your code gives you an extra entry. Good luck!",
      errorInvalid: "The referral code provided is invalid.",
      autoReferenceError:
        "You cannot use your own referral code to gain extra entries.",
    },
    errors: {
      generic: "An error occurred. Please try again.",
      login: "Login error",
      required: "Required field",
      notFound: "No data found",
      loading: "Loading...",
      duplicate:
        "This number has already participated in the last 24 hours. Try again later.",
      notRegistered: "Phone number not registered",
      referralDuplicate:
        "This number was already registered as a referral in this campaign.",
      otp: {
        invalid: "Invalid or unverified OTP",
        expired: "OTP has expired",
        resend: "You can try again in",
        resending: "Resending...",
        sent: "OTP sent",
      },
    },
    thankyou: {
      successTitle: "You're All Set!",
      successDescription:
        "Congratulations! You've been successfully entered into the Sweepstake.",
      main: "I'm participating to WIN a 2025 Nissan Versa at {{storeName}}! 🚗\n\nJoin the giveaway using this link! Each friend who registers gives us another chance to win. 👀👇\n{{referralLink}}",
      copySuccess: "Link copied!",
      shareMore:
        "Copy the link and send it via WhatsApp, Facebook, or wherever you want!",
      shareWhatsapp: "Share on WhatsApp",
      shareFacebook: "Share on Facebook",
      shareX: "Share on X (Twitter)",
      shareGmail: "Share via Gmail",
      copyLink: "Copy Link",
      copyright: "All rights reserved.",
    },
    navbar: {
      participate: "Participate",
      login: "Login",
      logout: "Logout",
    },
    otp: {
      title: "Verify Your Code",
      instruction: "Enter the 6-digit code sent to",
      fallbackPhone: "your number",
      noteStrong: "Check your messages!",
      note: "Enter the 6-digit code we sent you.",
      enterLabel: "Enter Verification Code",
      verified: "Code verified!",
      locked: "Too many attempts. Try again later.",
      attemptsLeft: "{{count}} attempts left",
      resendIn: "You can resend in",
      resendsLeft: "({{count}} left)",
      resending: "Sending...",
      resend: "Resend code",
      resendInline: "Didn't receive a code? Resend",
      notReceived:
        "Didn't receive the code? Check your number and your spam folder.",
    },
    worldcup: {
      hero: {
        topBanner: "FIFA WORLD CUP 2026 SWEEPSTAKE",
        win: "WIN 6",
        worldCup: "WORLD CUP",
        year: "2026™",
        ticketsFree: "TICKETS FOR FREE",
        prizeBreakdown: "PRIZE BREAKDOWN:",
        prize1: "4 tickets — MATCH",
        prize1Detail: "(Brazil vs Morocco)",
        prize2: "2 tickets — FINAL MATCH",
        prize3: "Teams & dates TBA",
        cta: "Enter Now",
        secondaryCta: "Learn More",
      },
      form: {
        title: "Win 6 WORLD CUP 2026 tickets",
      },
    },

    welcomeCoupon: {
      banner: {
        title: "Exclusive Offer",
        viewFull: "View Full Image",
        exclusiveLabel: "LIMITED TIME OFFER",
        defaultTitle: "OFFICIAL WELCOME DISCOUNT",
        defaultMessage: "Welcome! Present this coupon at the register for your exclusive benefit.",
        note: "Valid for first-time customers only. Fill out the form to get your code.",
        cta: "Register now",
        validity: "Validity",
        minPurchase: "Minimum Purchase",
        fastProcess: "Registration takes less than 30 seconds.",
      },
      form: {
        title: "Get your welcome coupon",
        subtitle: "Fill out your details to receive your promo code via SMS.",
        firstName: "First Name *",
        lastName: "Last Name *",
        phone: "Phone (10 digits) *",
        email: "Email (optional)",
        zip: "ZIP Code (optional)",
        referral: "Have a referral code? (optional)",
        referralHide: "Hide referral code",
        referralLabel: "Referral code",
        submit: "Get my coupon",
        privacy: "By registering, you agree to receive communications from the store.",
        errors: {
          firstName: "First name is required",
          lastName: "Last name is required",
          phone: "Phone is required",
          phoneDigits: "Enter 10 digits without spaces",
          email: "Invalid email",
        }
      },
      success: {
        title: "Coupon Generated!",
        welcome: "Welcome! 🎉",
        alreadyKnow: "We know you! 🥳",
        partOfStore: "You're now part of {{storeName}}",
        participating: "You are already participating in {{sweepstakeName}}",
        alreadyRegistered: "You're already registered at the store",
        yourCouponCode: "Your coupon code",
        yourParticipationNumber: "Your participation number",
        copyCode: "Copy code",
        copied: "Copied!",
        noSweepstake: "You're already registered at {{storeName}}. There are no active sweepstakes right now, but we'll notify you when one starts. 🔔",
        screenshotTitle: "📸 Take a screenshot!",
        screenshotNoteNew: "Show this coupon at the register to claim your benefit. You'll also receive a text message with your code.",
        screenshotNoteExisting: "Save your participation number. You'll receive an SMS with sweepstake details.",
        referralCodeLabel: "Your referral code: {{code}}",
        referralNote: "Share your code to earn extra entries when your friends sign up.",
        close: "Got it! 🎉",
      },
      errors: {
        pageUnavailable: "Page Unavailable",
        noActiveCoupon: "This store does not have active welcome coupons.",
        goHome: "Back to Home",
      }
    }
  },
};

export default en;