const es = {
  translation: {
    common: {
      welcome: "Bienvenido",
      submit: "Enviar",
      cancel: "Cancelar",
      yes: "Sí",
      no: "No",
      next: "Siguiente",
      prev: "Anterior",
    },
    referralStep: {
      step1: "Tu Información",
      step2: "Código de Referido",
      step3: "Verificar Código",
      title: "¡Gana un Nissan Versa 2025!",
      proccesing: "Procesando tu registro...",
    },
    weeklyTv: {
      form: {
        title: "Sorteo semanal de Smart TV",
        subtitle: 'Gana una Smart TV nueva de 55" - ¡Participa ahora para tener tu oportunidad!',
        note: "Todos los campos son obligatorios. Solo teléfono y ZIP de EE. UU.",
      },
    },
    winATv: {
      title: "Gana una TV de 55'' - 25 de Diciembre",
      notConfigured: "Este sorteo aún no está configurado. Vuelve pronto.",
    },
    login: {
      title: "Inicia sesión con tu teléfono",
      phoneLabel: "Número de teléfono",
      sendOtp: "Enviar OTP",
      enterOtp: "Ingresa el código OTP enviado a",
      verifyOtp: "Verificar OTP",
      changePhone: "Cambiar número",
      errorInvalidPhone: "Número no registrado",
      errorInvalidOtp: "OTP inválido",
      loading: "Cargando...",
    },
    home: {
      registerInStore: "Regístrate en nuestra tienda",
    },
    store: {
      openInMaps: "Abrir en Google Maps",
    },
    form: {
      firstName: "Nombre",
      lastName: "Apellido",
      phone: "Teléfono",
      email: "Correo electrónico",
      zip: "Código postal",
      referralCode: "Código de referido",
      referralCodeNotice: "Si no tienes uno, puedes darle al siguiente paso.",
      supermarket: "Supermercado",
      selectSupermarket: "Ingresa el nombre del supermercado",
      referralInfoTitle: "Información de referido",
      referralInfoSubtitle: "Ayúdanos a rastrear tu referido",
      referralCodePlaceholder: "¿TIENES UN CÓDIGO? AGRÉGALO AQUÍ",
      errors: {
        firstName: {
          required: "El nombre es obligatorio",
          max: "El nombre debe tener menos de 50 caracteres",
        },
        lastName: {
          required: "El apellido es obligatorio",
          max: "El apellido debe tener menos de 50 caracteres",
        },
        phone: "El número de teléfono debe tener el formato (123) 456-7890",
        email: "Ingresa un correo electrónico válido",
        zip: "El código postal debe tener 5 dígitos",
        otp: "El código OTP debe tener exactamente 6 dígitos",
        supermarket: {
          required: "Selecciona un supermercado",
          missingSweepstake: "Falta configuración del sorteo",
        },
      },
    },
    profile: {
      title: "Tu perfil",
      coupons: "Tus participaciones",
      referralLink: "Tu enlace de referido",
      referralCode: "Tu código de referido",
      copyLink: "Copiar enlace",
      copyCode: "Copiar código",
      registeredFriends: "Amigos registrados con tu link",
      noReferrals:
        "Aún no tienes referidos registrados. ¡Comparte tu link para sumar más oportunidades!",
      selectStore: "Selecciona tienda",
      shareWhatsapp: "Compartir por WhatsApp",
      shareFacebook: "Compartir en Facebook",
      share: "Compartir",
      mainReferralLink: "Enlace de referido",
      copySuccess: "¡Enlace copiado!",
      codeCopySuccess: "Código copiado al portapapeles",
      inviteMore: "¡Sigue compartiendo y mucha suerte en el sorteo!",
    },
    referral: {
      shareTitle: "¡Invita, comparte y gana!",
      shareDescription:
        "Comparte tu enlace exclusivo y multiplica tus oportunidades.",
      copy: "¡Copia el link y mándalo por WhatsApp, Messenger, Facebook, SMS, donde quieras!",
      referralExtra:
        "Cada amigo que se registre usando tu código te dará un cupón extra. ¡Suerte!",
      errorInvalid: "El código de referido proporcionado no es válido.",
      autoReferenceError:
        "No puedes usar tu propio código de referido para obtener un cupón extra.",
    },
    errors: {
      generic: "Ocurrió un error. Intenta de nuevo.",
      login: "Error al iniciar sesión",
      required: "Campo requerido",
      notFound: "No se encontraron datos",
      loading: "Cargando...",
      duplicate:
        "Este número ya ha participado en las últimas 24 horas. Inténtalo más tarde.",
      notRegistered: "Número no registrado",
      referralDuplicate:
        "Este número ya fue registrado como referido por esta campaña.",
      otp: {
        invalid: "OTP inválido o no verificado",
        expired: "El OTP ha expirado",
        resend: "Puedes intentar de nuevo en",
        resending: "Reenviando...",
        sent: "OTP enviado",
      },
    },
    thankyou: {
      successTitle: "¡Ya estás dentro!",
      successDescription:
        "¡Felicidades! Tu participación en el sorteo se registró correctamente.",
      main: "¡Estoy participando para GANAR un Nissan Versa 2025 en {{storeName}}! 🚗\n\n¡Súmate al sorteo usando este link! Cada amigo que se registre nos dará una oportunidad extra de ganar. 👀👇\n{{referralLink}}",
      copySuccess: "¡Link copiado!",
      shareMore:
        "¡Copia el link y mándalo por WhatsApp, Facebook, o donde quieras!",
      shareWhatsapp: "Compartir en WhatsApp",
      shareFacebook: "Compartir en Facebook",
      shareX: "Compartir en X (Twitter)",
      shareGmail: "Compartir por Gmail",
      copyLink: "Copiar link",
      copyright: "Todos los derechos reservados.",
    },
    navbar: {
      participate: "Participar",
      login: "Iniciar sesión",
      logout: "Cerrar sesión",
    },
    otp: {
      title: "Verifica tu código",
      instruction: "Ingresa el código de 6 dígitos enviado a",
      fallbackPhone: "tu número",
      noteStrong: "Revisa tus mensajes!",
      note: "Ingresa el código de 6 dígitos que te enviamos.",
      enterLabel: "Ingresa el código de verificación",
      verified: "¡Código verificado!",
      locked: "Demasiados intentos. Intenta más tarde.",
      attemptsLeft: "{{count}} intentos restantes",
      resendIn: "Puedes reenviar en",
      resendsLeft: "({{count}} restantes)",
      resending: "Enviando...",
      resend: "Reenviar código",
      resendInline: "¿No recibiste un código? Reenviar",
      notReceived:
        "¿No recibiste el código? Revisa tu número y la carpeta de spam.",
    },
    worldcup: {
      hero: {
        topBanner: "SORTEO FIFA WORLD CUP 2026",
        win: "GANA 6",
        worldCup: "WORLD CUP",
        year: "2026™",
        ticketsFree: "BOLETOS GRATIS",
        prizeBreakdown: "DESGLOSE DE PREMIOS:",
        prize1: "4 boletos — PARTIDO",
        prize1Detail: "(Brasil vs Marruecos)",
        prize2: "2 boletos — FINAL",
        prize3: "Equipos y fechas por confirmar",
        cta: "Participar Ahora",
        secondaryCta: "Más Información",
      },
      form: {
        title: "Gana 6 boletos de la WORLD CUP 2026",
      },
    },

    welcomeCoupon: {
      banner: {
        title: "Oferta exclusiva",
        viewFull: "Ver Imagen Completa",
        exclusiveLabel: "OFERTA POR TIEMPO LIMITADO",
        defaultTitle: "DESCUENTO OFICIAL DE BIENVENIDA",
        defaultMessage: "¡Bienvenido! Presenta este cupón en caja para tu beneficio exclusivo.",
        note: "Válido solo la primera vez. Llena el formulario para obtener tu código.",
        cta: "Regístrate ahora",
        validity: "Validez",
        minPurchase: "Compra Mínima",
        fastProcess: "El registro toma menos de 30 segundos.",
      },
      form: {
        title: "Obtén tu cupón de bienvenida",
        subtitle: "Completa tus datos para recibir tu código promocional por SMS.",
        firstName: "Nombre *",
        lastName: "Apellido *",
        phone: "Teléfono (10 dígitos) *",
        email: "Email (opcional)",
        zip: "Código postal (opcional)",
        referral: "¿Tienes un código de referido? (opcional)",
        referralHide: "Ocultar código de referido",
        referralLabel: "Código de referido",
        submit: "Obtener mi cupón",
        privacy: "Al registrarte aceptas recibir comunicaciones de la tienda.",
        errors: {
          firstName: "El nombre es requerido",
          lastName: "El apellido es requerido",
          phone: "El teléfono es requerido",
          phoneDigits: "Ingresa 10 dígitos sin espacios",
          email: "Email no válido",
        }
      },
      success: {
        title: "¡Cupón Generado!",
        welcome: "¡Bienvenido! 🎉",
        alreadyKnow: "¡Ya te conocemos! 🥳",
        partOfStore: "Ahora eres parte de {{storeName}}",
        participating: "Ya estás participando en {{sweepstakeName}}",
        alreadyRegistered: "Ya estás registrado en la tienda",
        yourCouponCode: "Tu código de cupón",
        yourParticipationNumber: "Tu número de participación",
        copyCode: "Copiar código",
        copied: "¡Copiado!",
        noSweepstake: "Ya estás registrado en {{storeName}}. No hay sorteos activos en este momento, pero te avisaremos cuando comience uno. 🔔",
        screenshotTitle: "📸 ¡Toma una captura de pantalla!",
        screenshotNoteNew: "Muestra este cupón en caja para reclamar tu beneficio. También recibirás un mensaje de texto con tu código.",
        screenshotNoteExisting: "Guarda tu número de participación. Recibirás un SMS con los detalles del sorteo.",
        referralCodeLabel: "Tu código de referido: {{code}}",
        referralNote: "Comparte tu código para ganar cupones extra cuando tus amigos se registren.",
        close: "¡Entendido! 🎉",
      },
      errors: {
        pageUnavailable: "Página no disponible",
        noActiveCoupon: "Esta tienda no tiene cupones de bienvenida activos.",
        goHome: "Volver al inicio",
      }
    }
  },
};

export default es;